version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: orion_prometheus
    network_mode: "container:wg-easy"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: orion_grafana
    network_mode: "container:wg-easy"
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: ""
    depends_on:
      - prometheus
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

  pushgateway:
    image: prom/pushgateway:latest
    container_name: orion_pushgateway
    network_mode: "container:wg-easy"
    ports:
      - "9091:9091"
    restart: always

volumes:
  grafana-data:
