services:
  prometheus:
    image: prom/prometheus:latest
    container_name: orion_prometheus
    network_mode: "container:wg-easy"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.listen-address=:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - prometheus-data:/prometheus
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: orion_grafana
    network_mode: "container:wg-easy"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_INSTALL_PLUGINS: ""
      GF_SERVER_HTTP_PORT: ${GRAFANA_HTTP_PORT}
    depends_on:
      - prometheus
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources/prod:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

  pushgateway:
    image: prom/pushgateway:latest
    container_name: orion_pushgateway
    network_mode: "container:wg-easy"
    command:
      - '--web.listen-address=:9092'
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    container_name: orion_alertmanager
    network_mode: "container:wg-easy"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - ./alertmanager/alertmanager.prod.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager-data:/alertmanager
    restart: always

  alertmanager-discord:
    build: ./alertmanager-discord
    container_name: orion_alertmanager_discord
    network_mode: "container:wg-easy"
    environment:
      DISCORD_WEBHOOK: ${DISCORD_WEBHOOK_URL}
    restart: always

  loki:
    image: grafana/loki:latest
    container_name: orion_loki
    network_mode: "container:wg-easy"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: always

  promtail:
    image: grafana/promtail:latest
    container_name: orion_promtail
    network_mode: "container:wg-easy"
    volumes:
      - ./promtail/promtail-config.prod.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: always

  chaosd:
    build: ./chaosd-daemon
    container_name: orion_chaosd
    network_mode: "container:wg-easy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - chaosd-data:/var/lib/chaosd
    privileged: true
    restart: always

  chaosd-ui:
    build: ./chaosd-ui
    container_name: orion_chaosd_ui
    network_mode: "container:wg-easy"
    environment:
      CHAOSD_URL: "http://localhost:31767"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - chaosd
    restart: always

volumes:
  grafana-data:
  prometheus-data:
  alertmanager-data:
  loki-data:
  chaosd-data:
